"use strict";
exports.LANG_EN_NAME = 'en';
exports.LANG_EN_TRANS = {
    //Login
    WELCOMETO: 'Welcome to XAS Mobile DMS',
    LOGINFORM: 'Login form',
    USERNAME: 'User Name',
    USERNAMEREREQUIERD: 'User name is requierd',
    PASSWORD: 'Password',
    PASSWORDREQUIERD: 'Password is required',
    REMEMBERME: 'Remember me',
    LOGIN: 'Login',
    ENTERUSERNAME: 'Enter User Name',
    ENTERPASSWORD: 'Enter Password',
    //HEADER: 
    HELLO: 'Hello',
    CHANGELNG: 'Change language',
    ENGLISH: 'English',
    GERMAN: 'German',
    LOGOFF: 'Logoff',
    CREATENEWUSER: 'Create New User',
    //dashbourd: 
    REGISTER: 'Register',
    JOBCARD: 'Job Card',
    ADMIN: 'Admin',
    PENDING: 'Pending items',
    //register: 
    REGISTERFORM: 'Register form',
    EMAIL: 'Email',
    EMAILREQUIERD: 'Email is required',
    EMAILINVALID: 'Email is invalid',
    PASSWORDIVALID: 'Password must be at least 6 chars long, containing lowercase letter and a digit',
    CONFIRMPASSWORD: 'Confirm password',
    CONFIRMPASSWORDQUIERD: 'Confirm password is required',
    CONFIRMPASSNOTEQUAL: 'Confirm password is not equal to password',
    CLEAR: 'Clear form',
    USERNAMEUSED: 'This username is already been used',
    EMAILUSED: 'This email is already been used',
    DEPCODE: 'Department code',
    DEPCODEREREQUIERD: 'Department code is required',
    EMPID: 'Employee ID',
    EMPIDREQUIERD: 'Employee ID is required',
    SAPDB: 'Sap Database',
    SAPDBREQUIERD: 'Sap Database is required',
    //Job Card: 
    TIMEREPORTING: 'Time Reporting',
    CHECKLIST: 'Check List',
    REALTIMEUPDATE: 'Real time update',
    OFFTIMEUPDATE: 'Off Time Update',
    STARTTASK: 'start task',
    REPORTDONETASK: 'report done task',
    PICKDATE: 'Pick a date',
    STARTTIME: 'Start time',
    ENDTIME: 'End time',
    REFRESH: 'Refresh',
    //CHECKLIST: 
    U_CarID: 'Vehicle Id',
    U_OwnBP: 'Customer Code',
    U_OwnBPN: 'Customer Name',
    U_OwnCnt: 'Contact',
    U_OwnCntPh: 'Phone',
    U_SpnsrBP: 'Spnsor Customer',
    U_SpnsrBPN: 'Sponser Customer Name',
    U_SpnsrCnt: 'Sponser Contact',
    U_SpnCntPh: 'Sponser Phone',
    U_Km: 'Mileage',
    U_Alarm: 'Sec. Code',
    U_Notes: 'Notes',
    U_Subject: 'Customer Concerns',
    U_VCode: 'VIN',
    U_FuelTank: 'Fuel Tank',
    U_EntryDt: 'Entriy Date',
    U_EntryHr: 'Entry Hour',
    U_DueDate: 'Due Date',
    U_DueTime: 'Due Time',
    U_LicNum: 'Licence Number',
    //Time Reporting
    NOTSTARTED: '(not started)',
    SUBMIT: 'Submit'
};
//# sourceMappingURL=lang-en.js.map